services:
  - type: web
    name: hobbyservers-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: HOBBYSERVERS_API_URL
        value: http://31.56.65.76:25576
      - key: HOBBYSERVERS_API_KEY
        sync: false
      - key: PORT
        value: 3001
